services:
  hospital-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__db_connection=Server=host.docker.internal,1433;Database=HospitalSystem;User Id=sa;Password=root;MultipleActiveResultSets=true;TrustServerCertificate=True;
    networks:
      - hospital-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "root"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - hospital-network

networks:
  hospital-network:
